version: '3.7'
services:
  database:
    image: postgres:10.4
    restart: always
    container_name: database
    volumes:
      - ./data/weather.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=nlmk
      - POSTGRES_USER=nlmk
      - POSTGRES_PASSWORD=nlmk

  web:
    build: ./web
    ports:
      - 5000:5000
    environment:
      - DB_PORT=5432
      - DB_VENDOR=postgres
      - DATABASE_LOCATION=database
      - POSTGRES_DB=nlmk
      - POSTGRES_USER=nlmk
      - POSTGRES_PASSWORD=nlmk

  ui:
    build: ./ui
    ports:
      - 80:80
    stdin_open: true
volumes:
  postgres-data:
